#!/usr/bin/env bash
DMEDITOR="st -e nvim"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"bspwm - $HOME/.config/bspwm/bspwmrc"
"dunst - $HOME/.config/dunst/dunstrc"
"dwm - $HOME/dwm/config.def.h"
"dwmblocks - $HOME/dwmblocks/blocks.def.h"
"i3 - $HOME/i3/config"
"neovim - $HOME/.config/nvim/init.vim"
"picom - $HOME/.config/picom/picom.conf"
"polybar - $HOME/.config/polybar/config"
"st - $HOME/st/config.def.h"
"termite - $HOME/.config/termite/config"
"xresources - $HOME/.Xresources"
"zsh - $HOME/.zshrc"
"quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20  -fn 'Terminus-10.5')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 1

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 1
fi
