#!/usr/bin/env bash
# j4-dmenu-desktop --dmenu="dmenu -i -fn 'Iosevka Term SS08 Medium-13' -nb '#282828' -nf '#bebebe' -sb '#83A595' -sf '#282828'"
# j4-dmenu-desktop --dmenu="dmenu -fn 'Terminus' -bw 3 -c -l 10 -p '>' -sb '#504945' "

# j4-dmenu-desktop --dmenu="dmenu -fn 'curie' -b -p '> ' "

# gruvbox-light
# j4-dmenu-desktop --dmenu="dmenu -fn 'curie' -b -p '> ' -nb '#E3CC94' -sf '#282828' -sb '#D79921' -nf '#282828' "

# nord
# j4-dmenu-desktop --dmenu="dmenu -fn 'curie' -p '> ' -nb '#2E3440' -sf '#282828' -sb '#81A1C1' -nf '#bebebe' "

# catppuccin
j4-dmenu-desktop --dmenu="dmenu -fn 'curie' -p '> ' -nb '#1e1e2e' -sf '#282828' -sb '#b48ead' -nf '#bebebe' "
